# Generated by Django 5.1.1 on 2025-06-25 10:40

import django.db.models.deletion
import django.utils.timezone
import resto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_stock', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address_default', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('hire', 'hire'), ('freelance', 'freelance')], max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('one', 'subscription'), ('con', 'contract')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('1', 'Writing'), ('2', 'Design'), ('3', 'Development'), ('4', 'Marketing'), ('5', 'Management'), ('6', 'Data Entry'), ('7', 'Customer Service'), ('8', 'Translation'), ('9', 'others')], max_length=255)),
                ('payment_type', models.CharField(choices=[('1', 'Fixed Price'), ('2', 'Monthly')], max_length=255)),
                ('min_budget', models.CharField(max_length=150)),
                ('max_budget', models.CharField(max_length=150)),
                ('company_size', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500'), ('5', '500+')], max_length=255)),
                ('required_skills', models.CharField(max_length=400)),
                ('special_skills', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=1)),
                ('hourly_rate', models.FloatField()),
                ('languages', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('website_link', models.CharField(max_length=255)),
                ('linkdeln_link', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
