# Generated by Django 5.1.1 on 2025-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_budget',
            field=models.IntegerField(),
        ),
    ]
