# Generated by Django 5.1.1 on 2025-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='user_doc',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
