# Generated by Django 5.1.1 on 2025-07-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_alter_profile_bio_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
