# Generated by Django 5.1.1 on 2025-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_profile_linkdeln_link_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'rejected'), ('3', 'accepted')], default='accepted', max_length=15),
        ),
    ]
