# Generated by Django 5.1.1 on 2025-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0009_apply_applied_date_apply_salary_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'rejected'), ('3', 'accepted')], default='pending', max_length=15),
        ),
    ]
