# Generated by Django 5.1.1 on 2025-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0010_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
