# Generated by Django 5.1.1 on 2025-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0011_job_applied_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applied_date',
            new_name='posted_date',
        ),
    ]
